# This is a boilerplate parameters config generated for pipeline 'train'
# using Kedro 0.18.1.
#
# Documentation for this file format can be found in "Parameters"
# Link: https://kedro.readthedocs.io/en/0.18.1/kedro_project_setup/configuration.html#parameters

dataset_params:
  num_labels: 3
  # train: training_set_oversampled
  # test: test_set
  # validation: validation_set


model_params:
  num_labels: 3
  num_train_epochs: 5
  batch_size: 256
  gradient_accumulation_steps: 8
  # learning_rate: 2e-5
  learning_rate: 0.00002
  weight_decay: 0.01
  # learning_rate: 0.01
  # test_data_ratio: 0.2
  # number_of_train_iterations: 10000
  # huggingface: str
  # dataset: str
  # wandb: str = None
  # max_length: int = 128
